### ISSUE TITLE
Approval checklist

### ISSUE THREAD

**Issue by knif3** [knif3/currencies-android#4]
### Teendők

* [x] Szimpla árfolyamváltás funkció, különféle valuták kiválasztása, aktuális árfolyamok lekérése API-ról
* [x] Numpad, ahol csak számok vannak, számolási funkciók nélkül
* [x] Regisztráció és belépés
* [ ] Utolsó árfolyampár lementése Firebase-el
* [x] Animációk (2) [??]
* [x] Lifecycle Hook [??]
* [x] Android permission (1) használata
* [x] Egy job scheduler (vagy notification vagy alarm manager) használata
* [ ] Minden CRUD művelet megvalósítva

Forrás: https://docs.google.com/spreadsheets/d/1LmJ5tbuoIwvx466fZ-zffX92gRoXDBI5iXqcjg1JrEY/edit#gid=976374229
